apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  name: pgvector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{.Release.Namespace}}
    app.kubernetes.io/instance: {{.Release.Namespace}}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgvector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgvector
    spec:
      containers:
        - name: pgvector
          image: quay.io/rh-aiservices-bu/postgresql-15-pgvector-c9s:latest
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - >
                    sleep 10;
                    psql -c 'create extension vector cascade;';
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: vector-database
                  key: DATABASE_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vector-database
                  key: DATABASE_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: vector-database
                  key: DATABASE_NAME
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vector-database
                  key: DATABASE_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: pgvector-storage
      volumes:
        - name: pgvector-storage
          persistentVolumeClaim:
            claimName: pgvector-pvc
