apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvector-pvc
  labels:
    app.kubernetes.io/name: {{.Release.Namespace}}
    app.kubernetes.io/instance: {{.Release.Namespace}}
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  #storageClassName: {{.Values.storageClass}}
  volumeMode: Filesystem
  #volumeName: pgvector-pv
