apiVersion: v1
kind: Service
metadata:
  name: pgvector-postgres-service
  labels:
    app.kubernetes.io/name: {{.Release.Namespace}}
    app.kubernetes.io/instance: {{.Release.Namespace}}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: pgvector
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
