apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  name: {{.Values.applicationName}}-web-application-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentic-ai-query.primary-labels" $ | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
       app.kubernetes.io/name: agentic-ai-query-web-application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: agentic-ai-query-web-application
    spec:
      containers:
        - name: agentic-ai-query-web-application
          image: 'docker.io/psamouelian/agentic-ai-query:latest'
          ports:
            - containerPort: 8501
              protocol: TCP
          env:
            - name: S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: s3-model-storage
                  key: AWS_S3_ENDPOINT
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: s3-model-storage
                  key: AWS_S3_BUCKET
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-model-storage
                  key: AWS_DEFAULT_REGION
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-model-storage
                  key: AWS_ACCESS_KEY_ID
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-model-storage
                  key: AWS_SECRET_ACCESS_KEY
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: vector-database
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vector-database
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: vector-database
                  key: DATABASE_NAME
