kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: agentic-ai-query
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/instance: agentic-ai-query
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: agentic-ai-query
    helm.sh/chart: agentic-ai-query-0.1.0
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: agentic-ai-query-{{.Release.Namespace}}.apps.{{.Values.node-name}}
  to:
    kind: Service
    name: agentic-ai-query-web-application-service
    weight: 100
  port:
    targetPort: 8501-http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
