apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.applicationName }}-service-account
  labels:
    {{- include "agentic-ai-query.primary-labels" $ | indent 4 }}
  namespace: {{ .Release.Namespace }}