apiVersion: v1
kind: Secret
metadata:
  name: vector-database
  labels:
    opendatahub.io/dashboard: 'true'
    app.kubernetes.io/name: {{.Release.Name}}
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: Helm
data:
  DATABASE_USER: cG9zdGdyZXM=
  DATABASE_PASSWORD: cG9zdGdyZXM=
  DATABASE_NAME: cG9zdGdyZXM=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: inference
  labels:
    opendatahub.io/dashboard: 'true'
    app.kubernetes.io/name: {{.Release.Name}}
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: Helm
data:
  GENERATIVE_MODEL_NAME: bGxhbWEtMzEtOGItaW5zdHJ1Y3Q=
  GENERATIVE_ENDPOINT: aHR0cHM6Ly9sbGFtYS0zMS04Yi1pbnN0cnVjdC1zYW1vdWVsaWFuLWVkYi1haS5hcHBzLmFpLWRldjAxLmtuaS5zeXNlbmcuZGV2Y2x1c3Rlci5vcGVuc2hpZnQuY29t
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: s3-model-storage
  namespace: samouelian-intel
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    opendatahub.io/connection-type-ref: s3
    openshift.io/description: ''
    openshift.io/display-name: s3-model-storage
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_DEFAULT_REGION: dXMtZWFzdC0x
  AWS_S3_BUCKET: ZWRiLWFpZGI=
  AWS_S3_ENDPOINT: aHR0cHM6Ly9taW5pby1hcGktbWluaW8uYXBwcy5haS1kZXYwMS5rbmkuc3lzZW5nLmRldmNsdXN0ZXIub3BlbnNoaWZ0LmNvbQ==
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM0IQ==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-dspa-secret
  labels:
    opendatahub.io/dashboard: 'true'
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM0IQ==
type: Opaque

