apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: 'true'
    opendatahub.io/image-display-name: Standard Data Science
    notebooks.opendatahub.io/oauth-logout-url: 'https://rhods-dashboard-redhat-ods-applications.apps.{{.Values.hostName}}/projects/{{.Release.Namespace}}?notebookLogout=workbench'
    opendatahub.io/accelerator-name: ''
    openshift.io/description: ''
    openshift.io/display-name: workbench
    notebooks.opendatahub.io/last-image-selection: 's2i-generic-data-science-notebook:2025.1'
    notebooks.opendatahub.io/last-size-selection: Large
    opendatahub.io/username: 'kube:admin'
    opendatahub.io/hardware-profile-name: ''
  name: workbench
  namespace: redhat-ahead
  labels:
    app: workbench
    opendatahub.io/dashboard: 'true'
    opendatahub.io/odh-managed: 'true'
    opendatahub.io/user: kube-3aadmin
spec:
  template:
    spec:
      initContainers:
        - name: clone-notebook-repo
          image: alpine/git
          command:
            - /bin/sh
            - -c
            - |
              echo "Cleaning /opt/app-root/src..." && \
              rm -rf /opt/app-root/src/* && \
              echo "Cloning repo..." && \
              git clone {{ .Values.workbenchRepo }} /tmp/notebook && \
              cp -r /tmp/notebook/* /opt/app-root/src && \
              rm -rf /tmp/notebook
          volumeMounts:
            - name: workbench-storage
              mountPath: /opt/app-root/src
      containers:
        - resources:
            limits:
              cpu: '14'
              memory: 56Gi
            requests:
              cpu: '7'
              memory: 56Gi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/{{.Release.Namespace}}/workbench/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: workbench
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/{{.Release.Namespace}}/workbench/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                                  --ServerApp.token=''
                                  --ServerApp.password=''
                                  --ServerApp.base_url=/notebook/{{.Release.Namespace}}/workbench
                                  --ServerApp.quit_button=False
                                  --ServerApp.tornado_settings={"user":"kube-3aadmin","hub_host":"https://rhods-dashboard-redhat-ods-applications.apps.{{.Values.hostName}}","hub_prefix":"/projects/{{.Release.Namespace}}"}
            - name: JUPYTER_IMAGE
              value: 's2i-generic-data-science-notebook:2025.1'
            - name: PIP_CERT
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: REQUESTS_CA_BUNDLE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: SSL_CERT_FILE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: PIPELINES_SSL_SA_CERTS
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: GIT_SSL_CAINFO
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/app-root/src/
              name: workbench-storage
            - mountPath: /dev/shm
              name: shm
            - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
              name: trusted-ca
              readOnly: true
              subPath: ca-bundle.crt
          envFrom:
            - secretRef:
                name: s3-model-storage
          image: 'quay.io/modh/odh-generic-data-science-notebook@sha256:5999547f847ca841fe067ff84e2972d2cbae598066c2418e236448e115c1728e'
          workingDir: /opt/app-root/src
        - resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: oauth-proxy
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8443
              name: oauth-proxy
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/oauth/config
              name: oauth-config
            - mountPath: /etc/tls/private
              name: tls-certificates
          image: 'registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4f8d66597feeb32bb18699326029f9a71a5aca4a57679d636b876377c2e95695'
          args:
            - '--provider=openshift'
            - '--https-address=:8443'
            - '--http-address='
            - '--openshift-service-account=workbench'
            - '--cookie-secret-file=/etc/oauth/config/cookie_secret'
            - '--cookie-expire=24h0m0s'
            - '--tls-cert=/etc/tls/private/tls.crt'
            - '--tls-key=/etc/tls/private/tls.key'
            - '--upstream=http://localhost:8888'
            - '--upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
            - '--email-domain=*'
            - '--skip-provider-button'
            - '--openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"workbench","namespace":"$(NAMESPACE)"}'
            - '--logout-url=https://rhods-dashboard-redhat-ods-applications.apps.{{.Values.hostName}}/projects/{{.Release.Namespace}}?notebookLogout=workbench'
      enableServiceLinks: false
      serviceAccountName: workbench
      volumes:
        - name: workbench-storage
          persistentVolumeClaim:
            claimName: workbench-pvc
        - emptyDir:
            medium: Memory
          name: shm
        - configMap:
            items:
              - key: ca-bundle.crt
                path: ca-bundle.crt
            name: workbench-trusted-ca-bundle
            optional: true
          name: trusted-ca
        - name: oauth-config
          secret:
            defaultMode: 420
            secretName: workbench-oauth-config
        - name: tls-certificates
          secret:
            defaultMode: 420
            secretName: workbench-tls
