kind: Secret #Should be replaced with ExternalSecret and use a cloud-based solution or something like Vault
apiVersion: v1
metadata:
  name: minio-secret
data:
  MINIO_ROOT_PASSWORD: bWluaW8xMjM0IQ==
  MINIO_ROOT_USER: bWluaW8=
type: Opaque
